[tool.coverage.run]
omit = [
    "colorpedia/cli.py",
    "colorpedia/version.py",
    "setup.py",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-s -vv -p no:warnings"
minversion = "6.0"
testpaths = ["tests"]

[tool.setuptools_scm]
write_to = "colorpedia/version.py"
